# Config for training ViT-B/16 using MAE on mammography.
trainer: !!python/object:mjepa.TrainerConfig
  batch_size: 64
  num_workers: 24 
  num_epochs: 500
  accumulate_grad_batches: 8

backbone: !!python/object:vit.ViTConfig
  in_channels: 1
  hidden_size: 768
  ffn_hidden_size: 3072
  patch_size: [16, 16]
  depth: 12
  num_attention_heads: 12
  activation: "srelu"
  bias: false
  attention_dropout: 0.1
  hidden_dropout: 0.1
  drop_path_rate: 0.1
  normalization: "RMSNorm"
  backend: te
  checkpoint: true
  num_cls_tokens: 0
  num_register_tokens: 16

mae: !!python/object:mjepa.MAEConfig
  predictor_depth: 5
  context_ratio: 0.5
  target_ratio: 0.25
  scale: 4

optimizer: !!python/object:mjepa.OptimizerConfig
  optimizer: "soap"
  lr: 0.0005
  weight_decay: 0.05
  betas: [0.85, 0.95]
  precondition_frequency: 10
  pct_start: 0.01
  base_momentum: 0.85
  max_momentum: 0.95
  div_factor: 10
  final_div_factor: 10000