# Config for training ViT-S/4 using MJEPA on CIFAR-10.
trainer: !!python/object:mjepa.TrainerConfig
  batch_size: 1024
  num_workers: 24 
  num_epochs: 1500
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 10

backbone: !!python/object:vit.ViTConfig
  in_channels: 3
  hidden_size: 384
  ffn_hidden_size: 1536
  patch_size: [4, 4]
  depth: 12
  num_attention_heads: 12
  activation: "srelu"
  bias: false
  attention_dropout: 0.1
  hidden_dropout: 0.1
  drop_path_rate: 0.1
  normalization: "RMSNorm"
  backend: te
  checkpoint: true
  num_cls_tokens: 0
  num_register_tokens: 8

augmentations: !!python/object:mjepa.AugmentationConfig
  mixup_prob: 0.2
  mixup_alpha: 1.0
  use_noise: true
  noise_prob: 0.1
  noise_clip: true
  invert_prob: 0.1
  solarize_prob: 0.1
  solarize_threshold: 0.5
  posterize_prob: 0.1
  posterize_bits: 6

jepa: !!python/object:mjepa.JEPAConfig
  loss_fn: "cosine"
  momentum: 0.99
  predictor_depth: 4
  context_ratio: 0.5
  target_ratio: 0.25
  scale: 2

optimizer: !!python/object:mjepa.OptimizerConfig
  lr: 0.0005
  weight_decay: 0.05
  betas: [0.85, 0.95]
  fused: true
  pct_start: 0.1
  base_momentum: 0.85
  max_momentum: 0.95
  div_factor: 100
  final_div_factor: 10000